version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./nltk_data:/app/nltk_data
      - ./index_store:/app/index_store 