services:
  - type: web
    name: chatbot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: PORT
        value: "10000"
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: chatbot-data
      mountPath: /app/data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    initialInstanceCount: 1
    numInstances: 1
