services:
  - type: web
    name: chatbot-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TRANSFORMERS_NO_TF
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: NLTK_DATA
        value: /tmp/nltk_data
    healthCheckPath: /
    autoDeploy: true
