services:
  - type: web
    name: chatbot-api
    env: docker
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
