services:
  - type: web
    name: reachout-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: NLTK_DATA
        value: /tmp/nltk_data
      - key: TRANSFORMERS_NO_TF
        value: 1
      - key: TOKENIZERS_PARALLELISM
        value: false
    healthCheckPath: /
    autoDeploy: true
