services:
  - type: web
    name: chatbot-api
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt', download_dir='/tmp/nltk_data')"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --limit-concurrency 5 --no-access-log --lifespan off --no-use-colors --loop uvloop
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: PORT
        value: "10000"
      - key: PYTHONPATH
        value: .
      - key: NLTK_DATA
        value: /tmp/nltk_data
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers
      - key: TORCH_HOME
        value: /tmp/torch
      - key: HF_HOME
        value: /tmp/huggingface
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: tmp-data
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    initialInstanceCount: 1
    numInstances: 1
