services:
  - type: web
    name: chatbot-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python -c "import nltk; nltk.download('punkt', download_dir='/tmp/nltk_data')" &&
      uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --limit-concurrency 10 --no-access-log --lifespan off
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: PORT
        value: "10000"
      - key: PYTHONPATH
        value: .
      - key: NLTK_DATA
        value: /tmp/nltk_data
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: chatbot-data
      mountPath: /app/data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    initialInstanceCount: 1
    numInstances: 1
